### ISSUE TITLE
Error while trying to instal core-happ

### ISSUE THREAD

**Issue by peeech** [Holo-Host/hpos-configure-holochain#136]
Holoport is following develop channel, currently at https://github.com/Holo-Host/holo-nixpkgs/commit/494c9089b07f6bf3084a397e6d765c7ffe276583. After registration there's a following error in the log:
```
Sep 02 08:38:20 hpos configure-holochain[105173]: Sep 02 08:38:20.515 ERROR run{config=Config { admin_port: 4444, happ_port: 42233, ui_store_folder: "/var/lib/configure-holochain/uis", happs_file_path: "/var/lib/configure-holochain/config.yaml" }}:install_and_activate_happ:register_and_install_happ: configure_holochain::websocket: error=error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos configure-holochain[105173]: Sep 02 08:38:20.515 ERROR run{config=Config { admin_port: 4444, happ_port: 42233, ui_store_folder: "/var/lib/configure-holochain/uis", happs_file_path: "/var/lib/configure-holochain/config.yaml" }}: configure_holochain: error=error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos configure-holochain[105173]: Error: error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos systemd[1]: configure-holochain.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 08:38:20 hpos systemd[1]: configure-holochain.service: Failed with result 'exit-code'.
Sep 02 08:38:20 hpos systemd[1]: Failed to start configure-holochain.service.
```

For more details log into a Holoport that is experiencing this issue: `172.26.64.140`

**Comment by peeech** [comment]
I spent a few hours reading through the code and trying to figure out what's wrong, to no success. Obviously it is a mismatch between a content of a file `/var/lib/configure-holochain/mem-proof-devNet-7f83bac1-fb97-4e0d-98d6-7888ef616de3` and what is hha's DNA expecting. I am unable to figure out though what exactly is wrong.

**Comment by alastairong** [comment]
@peeech 

These lines in configure-holochain overwrite the memproof file with a new one:
https://github.com/Holo-Host/hpos-configure-holochain/blob/1e39ba0e89b15451ee884bcc23a4b684c84e99bb/src/membrane_proof.rs#L133-L134

But the file was last updated 1st September 9:48 (when holo-auth ran) despite configure-holochain running every ~10 min
![image](https://user-images.githubusercontent.com/16625137/188107173-444880f4-75af-45c0-8ae2-46aa1a76bde0.png)

**Comment by alastairong** [comment]
![image](https://user-images.githubusercontent.com/16625137/188107790-6eafecb6-f3e1-4351-8232-2631310e72d1.png)

Changing permissions didn't help

**Comment by robbiecarlton** [comment]
> These lines in configure-holochain overwrite the memproof file with a new one:
> 
> https://github.com/Holo-Host/hpos-configure-holochain/blob/1e39ba0e89b15451ee884bcc23a4b684c84e99bb/src/membrane_proof.rs#L133-L134
> 

If those lines are being run, I think you should expect to see this log in the configure holochain log. 
https://github.com/Holo-Host/hpos-configure-holochain/blob/1e39ba0e89b15451ee884bcc23a4b684c84e99bb/src/membrane_proof.rs#L131

Worth checking if that's there

**Comment by peeech** [comment]
Those lines are never run, because of this code block:
https://github.com/Holo-Host/hpos-configure-holochain/blob/1e39ba0e89b15451ee884bcc23a4b684c84e99bb/src/websocket.rs#L85-L94
Each time service runs it checks for existence of agent key at `PUBKEY_PATH`. If it exists pub key is returned and execution of `get_agent_key()` is terminated.
As a consequence as long as a file under `PUBKEY_PATH` exists new memproof will never be fetched from the server. This leads to an error that we have encountered, where as soon as something changes in memproof holoport will fail to install core-happ.

**Comment by peeech** [comment]
Removing file at `PUBKEY_PATH`  resolved systemd errors on holoport.

**Comment by peeech** [comment]
Now my question is: is it a bug or undocumented behavior of `configure-holochain.service` on `devNet`? @alastairong @zo-el

**Comment by alastairong** [comment]
@zo-el I suspect that in dev-net we should just always be requesting a memproof rather than checking for existance of `PUBKEY_PATH`? Thoughts?

**Comment by zo-el** [comment]
I am not sure I understand the flaw you have stated. 
Yes, the function terminates when it finds the `PUBKEY_PATH` but every time the `PUBKEY_PATH` file is created the mem-proof is retrieved and saved. When means there is a valid mem-proof for the key that was stored.

The flaw I see is 
- the file should only be generated after the mem-proof is successfully retrieved.
- when using the key from the `PUBKEY_PATH` we also check the existence of a mem-proof. (This needs to be added because of the change made to the name of the mem-proof file, where when a holoport in devNet is running and receives a hashspace bump it expects to find a mem-proof at a different location than previously stored.)

**Comment by alastairong** [comment]
@peeech Reviewed this and figured out the issue.

Issue : When we bump hashspace in devnet, we are stuck with an invalid membrane proof for the CORRECT UID
1. We have a valid memproof for the random agent
2. The environment hashspace changes
3. We have an invalid memproof (invalid agent error)

Note that a memproof exists for this UID, so this is not an issue where the new memproof is not downloaded.

The issue is this:
1. When we force a random agent, we are able to get a special memproof for that agent:
https://github.com/Holo-Host/hpos-configure-holochain/blob/7146d1b1e40ed11ab50e1fbdf67b85088cb296d9/src/websocket.rs#L94-L110
2. The UID then changes
3. This line then looks for a new membrane proof: 
https://github.com/Holo-Host/hpos-configure-holochain/blob/7146d1b1e40ed11ab50e1fbdf67b85088cb296d9/src/lib.rs#L63
4. Which then triggers this code snippet:
https://github.com/Holo-Host/hpos-configure-holochain/blob/7146d1b1e40ed11ab50e1fbdf67b85088cb296d9/src/membrane_proof.rs#L114-L119
5. Note how step 4 calls `try_mem_proof_server_inner(None)`. That loads the agentKey from the config file
https://github.com/Holo-Host/hpos-configure-holochain/blob/7146d1b1e40ed11ab50e1fbdf67b85088cb296d9/src/membrane_proof.rs#L147-L158
6. And that leads us to have a memproof for the correct UID but the config file agent rather than the random agent.

And that's why when we delete the agent_key and memproof it works again - because then it re-runs step 1.
